<?php
session_start();
require 'C:\xampp\htdocs\SWAP_Assignment\AMC_Site\config\database_connection.php'; // Include the PDO connection file

// Check if user is logged in and has the appropriate role
if (!isset($_SESSION['user_id']) || !isset($_SESSION['role'])) {
    header("Location: login_form.php");
    exit();
}

$user_id = $_SESSION['user_id'];
$user_role = $_SESSION['role'];

// Initialize feedback message
$message = "";

// Handle delete report
if (isset($_POST['delete_report'])) {
    $report_id = $_POST['report_id'];
    if ($user_role === 'Admin') {
        $deleteStmt = $pdo->prepare("DELETE FROM reports WHERE report_id = :report_id");
        $deleteStmt->bindParam(':report_id', $report_id);
        $deleteStmt->execute();
        $message = "Report deleted successfully.";
    } else {
        $message = "You do not have permission to delete reports.";
    }
}

// Fetch all reports
$reports = $pdo->query("SELECT * FROM reports")->fetchAll(PDO::FETCH_ASSOC);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports Management</title>
    <link rel="stylesheet" href="../assets/styles/dashboard.css">
    <style>
        body {
            background: #F9F9F9;
            color: #333;
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container {
            background: #FFFFFF;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
            max-width: 800px;
            width: 100%;
            text-align: center;
            border: 1px solid #DDD;
        }
        h1, h2 {
            color: black;
        }
        .button {
            padding: 10px 20px;
            background-color: #D71920;
            color: #FFFFFF;
            text-decoration: none;
            border-radius: 6px;
            font-weight: bold;
            display: inline-block;
            margin: 10px 5px;
        }
        .button:hover {
            background-color: #B6161A;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 12px;
            border: 1px solid #DDD;
            text-align: left;
        }
        th {
            background: #F1F1F1;
            color: black;
        }
        td {
            background: #FFFFFF;
            color: black;
        }
        button {
            background: #FF5555;
            color: white;
            border: none;
            padding: 8px 12px;
            border-radius: 5px;
            cursor: pointer;
        }
        button:hover {
            background: #CC4444;
        }
        a.view-link, a.update-link {
            color: #0066CC;
            text-decoration: none;
            margin-left: 10px;
        }
        a.view-link:hover, a.update-link:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Reports Management</h1>
        <a href="create.php" class="button">Create New Report</a>
        <a href="../dashboard.php" class="button">Back to Dashboard</a>
        <div id="output">
            <?php if (!empty($message)) echo "<p>$message</p>"; ?>
        </div>
        <h2>Existing Reports</h2>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Report Name</th>
                    <th>Report Type</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($reports as $report): ?>
                    <tr>
                        <td><?php echo $report['report_id']; ?></td>
                        <td><?php echo htmlspecialchars($report['report_name']); ?></td>
                        <td><?php echo htmlspecialchars($report['report_type']); ?></td>
                        <td><?php echo htmlspecialchars($report['generated_by']); ?></td>
                        <td>
                            <form method="POST" style="display:inline;">
                                <input type="hidden" name="report_id" value="<?php echo $report['report_id']; ?>">
                                <button type="submit" name="delete_report">Delete</button>
                            </form>
                            <?php if ($user_role === 'Admin'): ?>
                                <a href="update.php?id=<?php echo $report['report_id']; ?>" class="update-link">Update</a>
                            <?php endif; ?>
                            <a href="view.php?id=<?php echo $report['report_id']; ?>" class="view-link">View</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</body>
</html>
